// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD75LIuBMMLf8aQ8WMLQ6Nlwx9P53ZzSVw',
    appId: '1:471672720430:web:3d88acf26fb91bf70223bf',
    messagingSenderId: '471672720430',
    projectId: 'food-ad0d3',
    authDomain: 'food-ad0d3.firebaseapp.com',
    storageBucket: 'food-ad0d3.firebasestorage.app',
    measurementId: 'G-FREGSRJ1WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC2Qo-Dfnt8aKsjGkbvC-3gpnQHsJHq0s',
    appId: '1:471672720430:android:85426a7aa3add16b0223bf',
    messagingSenderId: '471672720430',
    projectId: 'food-ad0d3',
    storageBucket: 'food-ad0d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tpMW0qmWifi440eZSaqCn6FglgkY1EQ',
    appId: '1:471672720430:ios:6764aa10fdfc83040223bf',
    messagingSenderId: '471672720430',
    projectId: 'food-ad0d3',
    storageBucket: 'food-ad0d3.firebasestorage.app',
    androidClientId: '471672720430-a2hqoaeuefae8up8a6o70e5qeuj191f6.apps.googleusercontent.com',
    iosClientId: '471672720430-u6fgr6n95sb6hrdgoejkdkch9sh781e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8tpMW0qmWifi440eZSaqCn6FglgkY1EQ',
    appId: '1:471672720430:ios:6764aa10fdfc83040223bf',
    messagingSenderId: '471672720430',
    projectId: 'food-ad0d3',
    storageBucket: 'food-ad0d3.firebasestorage.app',
    androidClientId: '471672720430-a2hqoaeuefae8up8a6o70e5qeuj191f6.apps.googleusercontent.com',
    iosClientId: '471672720430-u6fgr6n95sb6hrdgoejkdkch9sh781e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzKtfcYK95KoSfpEZEGf8R4hvcm0_9mHM',
    appId: '1:471672720430:web:bc42bb9c429563f30223bf',
    messagingSenderId: '471672720430',
    projectId: 'food-ad0d3',
    authDomain: 'food-ad0d3.firebaseapp.com',
    storageBucket: 'food-ad0d3.firebasestorage.app',
    measurementId: 'G-WZC982HRN9',
  );
}
